version: "3.8"

services:
  kafka-1:
    image: confluentinc/cp-kafka:7.7.7
    hostname: kafka1
    container_name: kafka1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "SourceClusterID-133331"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ${KAFKA_DATA_1_PATH}:/var/lib/kafka/data
      - kafka-1-logs:/app/logs
    networks:
      - service-network

  kafka-2:
    image: confluentinc/cp-kafka:7.7.7
    hostname: kafka2
    container_name: kafka2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka2:9092,CONTROLLER://kafka2:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "SourceClusterID-133331"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    ports:
      - 9094:9092
      - 9095:9093
    volumes:
      - ${KAFKA_DATA_2_PATH}:/var/lib/kafka/data
      - kafka-2-logs:/app/logs
    networks:
      - service-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092
    ports:
      - 8080:8080
    volumes:
      - kafka-ui-logs:/app/logs
    networks:
      - service-network
    depends_on:
      - kafka-1
      - kafka-2

  spark-master:
    build: 
      context: .
      dockerfile: containers/spark/maven/Dockerfile
    image: spark:latest
    container_name: spark-master
    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_MASTER_MEMORY: "1g"
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-master.sh"
    ports:
      - 8082:8080
      - 4040:4040
    volumes:
      - spark-master-logs:/app/logs
    networks:
      - service-network
    depends_on:
      - minio

  spark-worker:
    image: spark:latest
    container_name: spark-worker1
    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: "6g"
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077"
    volumes:
      - spark-workers-logs:/app/logs
    networks:
      - service-network
    depends_on:
      - minio

  spark-thrift-server:
    image: spark:latest
    container_name: spark-thrift-server
    environment:
      SPARK_NO_DAEMONIZE: "true"
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-thriftserver.sh spark://spark-master:7077
          --driver-memory 1g \
          --executor-memory 2g \
          --executor-cores 2 \
          --num-executors 1 \
          --conf spark.cores.max=2"
    ports:
      - 10000:10000
    volumes:
      - ./conf:/opt/spark/conf
      - spark-thrift-server-logs:/app/logs
    networks:
      - service-network
    depends_on:
      - spark-master
      - spark-worker

  spark-job1:
    build: 
      context: .
      dockerfile: containers/spark_job/Dockerfile
    image: spark-job:latest
    container_name: spark-job1
    env_file:
      - .env
    entrypoint: /bin/bash
    command: -c "spark-submit \
          --driver-memory 1g \
          --executor-memory 2g \
          --executor-cores 2 \
          --num-executors 2 \
          --conf spark.cores.max=2 \
          --conf spark.sql.shuffle.partitions=100 \
          --conf spark.streaming.kafka.maxRatePerPartition=500 \
          --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.8,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262,org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.10.0 \
          data_ingestion__kafka_to_minio.py"

    volumes:
      - ./conf:/opt/spark/conf
      - spark-job1-logs:/app/logs
    networks:
      - service-network
    depends_on:
      - spark-master
      - spark-worker
      - minio

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ${MINIO_PATH}:/data
      - minio-logs:/app/logs
    networks:
      - service-network 
    ports:
      - 9000:9000
      - 9001:9001

  mqtt-bridge:
    build: 
      context: .
      dockerfile: containers/thingspeak/Dockerfile
    image: mqtt_bridge:latest
    container_name: thingspeak-mqtt-bridge
    env_file:
      - .env
    volumes:
      - mqtt-bridge-logs:/app/logs
    networks:
      - service-network
    depends_on:
      - kafka-1
      - kafka-2

volumes:
  mqtt-bridge-logs:
  kafka-1-logs:
  kafka-2-logs:
  kafka-ui-logs:
  spark-master-logs:
  spark-workers-logs:
  spark-thrift-server-logs:
  spark-job1-logs:
  minio-logs:

networks:
  service-network:
    driver: bridge
